"""Candle Confirmation TP/SL sweep for the best USDJPY filter candidate."""

import contextlib
import io
import itertools
import logging
import sys

from backtest_engine import BacktestEngine
import config
from data.historical_loader import find_csv, load_and_merge
from strategies.candle_confirmation import CandleConfirmationStrategy

logging.basicConfig(level=logging.ERROR)
sys.stdout.reconfigure(line_buffering=True)

SYMBOLS = ['USDJPY']
INITIAL_BALANCE = 10_000.0
RR_RATIO = 2.5
TF_STACK = ('H1', 'M5')
PARAM_GRID = {
    'tp_range_pct': [0.75, 1.0, 1.25, 1.5, 2.0],
    'sl_mode': ['symmetric', 'mss_bar', 'structural'],
    'sl_rr_ratio': [1.0, 1.25, 1.5, 2.0],
    'min_sl_pips': [5.0, 8.0, 10.0, 12.0],
}


def main():
    tf_bias, tf_entry = TF_STACK
    csv_paths = []
    needed_tfs = {tf_bias, tf_entry, 'D1'}
    for symbol in SYMBOLS:
        for tf in sorted(needed_tfs):
            paths = find_csv(symbol, tf)
            if not paths:
                print(f"WARNING: no CSV found for {symbol} {tf}")
            csv_paths.extend(paths)

    if not csv_paths:
        print("No data found. Exiting.")
        return

    print("Loading bar data...")
    bars = load_and_merge(csv_paths)
    print(f"Loaded {len(bars):,} bars for {tf_bias}/{tf_entry}")

    keys = list(PARAM_GRID.keys())
    combos = [dict(zip(keys, values)) for values in itertools.product(*PARAM_GRID.values())]
    results = []

    print(f"Running {len(combos)} combinations...\n")
    for i, params in enumerate(combos, start=1):
        strategy = CandleConfirmationStrategy(
            tf_bias=tf_bias,
            tf_entry=tf_entry,
            fractal_n=2,
            retrace_pct=0.5,
            tp_range_pct=params['tp_range_pct'],
            sl_rr_ratio=params['sl_rr_ratio'],
            sl_mode=params['sl_mode'],
            require_fvg=True,
            min_sl_pips=params['min_sl_pips'],
            pip_sizes=dict(config.PIP_SIZE),
            tf_trend='D1',
            ema_fast=20,
            ema_slow=50,
            ema_sep_pct=0.0005,
            min_engulf_range_pips=8.0,
            min_engulf_body_pct=0.5,
            close_extreme_pct=1.0,
            require_engulf_color=False,
        )

        engine = BacktestEngine(initial_balance=INITIAL_BALANCE, rr_ratio=RR_RATIO)
        engine.add_strategy(strategy, symbols=SYMBOLS)

        with contextlib.redirect_stdout(io.StringIO()):
            for bar in bars:
                closed_trades = engine.execution.check_fills(bar)
                for trade in closed_trades:
                    engine.portfolio.record_close(
                        trade['symbol'], trade['pnl'], trade.get('strategy_name', '')
                    )
                    engine.trade_logger.log_close(trade['ticket'], trade)
                    engine.event_engine.notify_trade_closed(trade)
                engine.event_engine.process_bar(bar)

        trades = engine.execution.get_closed_trades()
        if not trades:
            continue

        results.append({**params, **_metrics(trades)})

        if i % 25 == 0 or i == len(combos):
            best = max((r['total_r'] for r in results), default=0.0)
            print(f"  {i}/{len(combos)} best total R so far: {best:+.1f}")

    _print_results(results)


def _metrics(trades):
    n = len(trades)
    wins = sum(1 for t in trades if t['result'] == 'WIN')
    total_r = sum(t['r_multiple'] for t in trades)
    gross_profit = sum(t['r_multiple'] for t in trades if t['result'] == 'WIN')
    gross_loss = abs(sum(t['r_multiple'] for t in trades if t['result'] == 'LOSS'))

    peak = running = max_dd = 0.0
    worst_streak = cur_streak = 0
    for trade in trades:
        running += trade['r_multiple']
        peak = max(peak, running)
        max_dd = max(max_dd, peak - running)
        if trade['result'] == 'LOSS':
            cur_streak += 1
            worst_streak = max(worst_streak, cur_streak)
        else:
            cur_streak = 0

    return {
        'trades': n,
        'win_rate': wins / n * 100.0,
        'total_r': total_r,
        'pf': gross_profit / gross_loss if gross_loss > 0 else 0.0,
        'expectancy': total_r / n,
        'max_dd_r': max_dd,
        'worst_streak': worst_streak,
    }


def _print_results(results):
    if not results:
        print("No closed trades generated by any combination.")
        return

    width = 150
    header = (
        f"{'tp':>5} {'sl_mode':>10} {'sl_rr':>5} {'min_sl':>6} | "
        f"{'trades':>6} {'WR%':>6} {'TotalR':>8} {'PF':>6} "
        f"{'Expect':>7} {'MaxDD':>6} {'Streak':>6}"
    )

    def row(r):
        return (
            f"{r['tp_range_pct']:>5.2f} {r['sl_mode']:>10} "
            f"{r['sl_rr_ratio']:>5.2f} {r['min_sl_pips']:>6.1f} | "
            f"{r['trades']:>6} {r['win_rate']:>5.1f}% {r['total_r']:>+8.1f} "
            f"{r['pf']:>6.2f} {r['expectancy']:>+7.3f} "
            f"{r['max_dd_r']:>6.1f} {r['worst_streak']:>6}"
        )

    def print_table(title, rows, limit=30):
        print(f"\n{'=' * width}")
        print(title)
        print('=' * width)
        print(header)
        print('-' * width)
        for r in rows[:limit]:
            print(row(r))

    by_total = sorted(results, key=lambda r: r['total_r'], reverse=True)
    print_table(f"TOP 30 BY TOTAL R ({len(results)} valid)", by_total)

    min_trades = [r for r in results if r['trades'] >= 30]
    by_expectancy = sorted(min_trades, key=lambda r: r['expectancy'], reverse=True)
    print_table("TOP 30 BY EXPECTANCY (min 30 trades)", by_expectancy)

    print(f"\n{'=' * width}")
    print("TP LEVEL IMPACT (avg expectancy, min 30 trades)")
    print('=' * width)
    for name in PARAM_GRID['tp_range_pct']:
        rows = [r for r in min_trades if r['tp_range_pct'] == name]
        if rows:
            avg = sum(r['expectancy'] for r in rows) / len(rows)
            best = max(r['expectancy'] for r in rows)
            print(f"  {name:>5.2f}: avg {avg:+.3f}R   best {best:+.3f}R   ({len(rows)} combos)")

    print(f"\n{'=' * width}")
    print("SL MODE IMPACT (avg expectancy, min 30 trades)")
    print('=' * width)
    for name in PARAM_GRID['sl_mode']:
        rows = [r for r in min_trades if r['sl_mode'] == name]
        if rows:
            avg = sum(r['expectancy'] for r in rows) / len(rows)
            best = max(r['expectancy'] for r in rows)
            print(f"  {name:>10}: avg {avg:+.3f}R   best {best:+.3f}R   ({len(rows)} combos)")


if __name__ == '__main__':
    main()
